name: feely
description: Feely - 감정 일기 앱. 감정 변화를 기록하고 시각적으로 확인합니다.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.19.0
  uuid: ^4.2.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  http: ^1.2.0
  geocoding: ^2.1.1
  flutter_naver_map: ^1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
